# Generated by Django 5.1 on 2024-08-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_order_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='order',
            new_name='user',
        ),
    ]
