# Generated by Django 5.1 on 2024-08-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='certificate',
            new_name='certificate_image',
        ),
    ]
