# Generated by Django 5.1 on 2024-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_certificate_freelancer_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="certificate_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
