# Generated by Django 5.1 on 2024-08-15 21:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_freelancer_certificate_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="avatar",
            field=models.ImageField(upload_to=accounts.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="certificate_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="certificate_image",
            field=models.ImageField(upload_to=accounts.models.user_certificate_path),
        ),
    ]
