# Generated by Django 5.1 on 2024-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_freelancer_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="freelancer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
