# Generated by Django 5.1 on 2024-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_is_verified_freelancer_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
