# Generated by Django 5.1 on 2024-08-20 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_freelancer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='internal_rating',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
