# Generated by Django 5.1 on 2024-08-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_freelancer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='is_active',
        ),
    ]
