# Generated by Django 5.1 on 2024-08-20 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_freelancer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatars/default_profile.png', upload_to=accounts.models.user_avatar_path),
        ),
    ]
