# Generated by Django 5.1 on 2024-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('billing', 'Billing'), ('compaint', 'Complaint'), ('suggestion', 'Suggestion'), ('feature_request', 'Feature Request'), ('other', 'Other')], default='General', max_length=255),
        ),
    ]
