# Generated by Django 5.1 on 2024-08-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('billing', 'Billing'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('feature_request', 'Feature Request'), ('other', 'Other')], default='general', max_length=255),
        ),
    ]
