# Generated by Django 5.1 on 2024-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_alter_comment_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_category",
            field=models.CharField(
                choices=[
                    ("general", "عامة"),
                    ("technical", "تقنية"),
                    ("billing", "الدفع"),
                    ("complaint", "شكوى"),
                    ("suggestion", "اقتراح"),
                    ("feature_request", "طلب اضافة ميزة"),
                    ("other", "اخرى"),
                ],
                default="general",
                max_length=255,
            ),
        ),
    ]
