# Generated by Django 5.1 on 2024-08-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='offer',
            new_name='order',
        ),
    ]
