# Generated by Django 5.1 on 2024-08-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('reviews', '0002_alter_review_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.offer'),
        ),
    ]
