# Generated by Django 5.1 on 2024-08-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AddField(
            model_name='offer',
            name='stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Processed', 'Processed'), ('Finalized', 'Finalized')], default='Pending', max_length=100),
        ),
    ]
