# Generated by Django 5.1 on 2024-08-19 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderimage_order_alter_ordervideo_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderimage",
            name="image",
            field=models.FileField(upload_to="order_images/"),
        ),
        migrations.AlterField(
            model_name="ordervideo",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
