# Generated by Django 5.1 on 2024-08-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_freelancer_avatar_account_avatar'),
        ('orders', '0003_alter_offer_appointment_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.freelancer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Discarded', 'Discarded'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Processed', 'Processed'), ('Finalized', 'Finalized')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.freelancer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Discarded', 'Discarded'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
