# Generated by Django 5.1 on 2024-08-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_category_offer_payment_alter_offer_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Discarded', 'Discarded'), ('Declined', 'Declined'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
