# Generated by Django 5.1 on 2024-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='proposed_service_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
