# Generated by Django 5.1 on 2024-08-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_offer_proposed_service_date_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='refund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20),
        ),
    ]
