# Generated by Django 5.1 on 2024-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_offer_refund_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='complete_on_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='proposed_service_date',
            field=models.DateField(),
        ),
    ]
